# Generated by Django 2.0.1 on 2018-01-23 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_article_nbrcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=42)),
                ('slug', models.SlugField()),
                ('description', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
                ('besoin_phys', models.BooleanField(default=False, verbose_name='Compétent en physique')),
                ('besoin_chim', models.BooleanField(default=False, verbose_name='Compétent en chimie')),
                ('besoin_math', models.BooleanField(default=False, verbose_name='Compétent en maths')),
            ],
        ),
        migrations.CreateModel(
            name='NiveauScolaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=42)),
                ('nom', models.CharField(max_length=42)),
                ('slug', models.SlugField()),
                ('description', models.TextField(null=True)),
                ('competence_phys', models.BooleanField(default=False, verbose_name='Compétent en physique')),
                ('competence_chim', models.BooleanField(default=False, verbose_name='Compétent en chimie')),
                ('competence_math', models.BooleanField(default=False, verbose_name='Compétent en maths')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='prof',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Profession'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='niveauScolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.NiveauScolaire'),
        ),
    ]
